name: pr-commit-message-enforcer-and-linker

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  pr-commit-message-enforcer-and-linker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Azure DevOps Commit Validator and Pull Request Linker
        uses: joshjohanning/azdo_commit_message_validator@test-v2.0.1
        with:
          azure-devops-organization: jjohanning0798 # The name of the Azure DevOps organization
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }} # "Azure DevOps Personal Access Token (needs to be a full PAT)
          fail-if-missing-workitem-commit-link: true # Fail the action if a commit in the pull request is missing AB# in the commit message
          link-commits-to-pull-request: true # Link the work items found in commits to the pull request
          check-commits: true
          check-pull-request: true
