name: pr-commit-message-enforcer-and-linker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr-commit-message-enforcer-and-linker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Azure DevOps Commit Validator and Pull Request Linker
        uses: joshjohanning/azdo_commit_message_validator@only-link-in-pr
        with:
          azure-devops-organization: jjohanning0798 # The name of the Azure DevOps organization
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }} # "Azure DevOps Personal Access Token (needs to be a full PAT)
          check-commits: true
          fail-if-missing-workitem-commit-link: true # Fail the action if a commit in the pull request is missing AB# in the commit message
          link-commits-to-pull-request: true # Link the work items found in commits to the pull request
          check-pull-request: false
